### ISSUE TITLE
`breakpoints` mixin

### ISSUE THREAD

**Issue by calvindavis** [yoyodesign/gort#9]
Some version of a breakpoints mixin.

I like this: http://breakpoint-sass.com/

We could potentially just use that? Or roll our own inspired by some of the nice conventions in Breakpoint, without the stuff we don't need (support for browsers without media queries, etc.).

**Comment by calvindavis** [comment]
I really like the concept from Breakpoint of **not** having predefined breakpoints in the library, but a convention that in each project we'll have a bunch of variables like...

```
$breakpoint-mobile: max-width 550px
$breakpoint-table: 551px 1024px
$breakpoint-desktop: 1025px 1920px
$breakpoint-hd: 1921px
```

These will be easy to find, easily modified per project, and easier to understand than a bunch of undocumented and cryptic names like `smed`, `med`, `meds`, etc.

**Comment by alfie-g** [comment]
I agree, I've never liked being forced to use pre-defined breakpoints, and sometimes have ended up just creating my own `sizes` file and using variable names that make sense to me, and I don't have to write them all down on a sticky note and have by my side at all times.
